### ISSUE TITLE
Setting freq

### ISSUE THREAD

**Issue by 777arc** [GvozdevLeonid/python_hackrf#2]
Trying to set freq to 100 MHz, `pyhackrf_set_freq(100e6)` didn't seem to be doing anything, so switching to `pyhackrf_set_freq_explicit` I tried:

```
from python_hackrf import pyhackrf
pyhackrf.pyhackrf_init()
sdr = pyhackrf.pyhackrf_open()
sdr.pyhackrf_set_sample_rate_manual(10e6, 1)
sdr.pyhackrf_set_freq_explicit(100e6, 100e6, pyhackrf.py_rf_path_filter.RF_PATH_FILTER_BYPASS)
```

but on that last line I'm getting the error:

```
File "python_hackrf/pylibhackrf/pyhackrf.pyx", line 277, in python_hackrf.pylibhackrf.pyhackrf.PyHackrfDevice.pyhackrf_set_freq_explicit
RuntimeError: pyhackrf_set_freq_explicit() failed: invalid parameter(s) (-2)
```

**Comment by GvozdevLeonid** [comment]
It seems that `pyhackrf_set_freq` should work correctly. If you don't see any errors, it should work.

Regarding `pyhackrf_set_freq_explicit`, here is the documented line for that function:
```
/**
* Set the center frequency via explicit tuning
*
* Center frequency is set to \f$f_{center} = f_{IF} + k\cdot f_{LO}\f$ where \f$k\in\left\{-1; 0; 1\right\}\f$, depending on the value of @p path. See the documentation of @ref rf_path_filter for details
*
* @param device device to tune
* @param if_freq_hz tuning frequency of the MAX2837 transceiver IC in Hz. Must be in the range of 2150-2750MHz
* @param lo_freq_hz tuning frequency of the RFFC5072 mixer/synthesizer IC in Hz. Must be in the range 84.375-5400MHz, defaults to 1000MHz. No effect if @p path is set to @ref RF_PATH_FILTER_BYPASS
* @param path filter path for mixer. See the documentation for @ref rf_path_filter for details
* @return @ref HACKRF_SUCCESS on success or @ref hackrf_error variant
* @ingroup configuration
*/
```
So you can call 
```
sdr.pyhackrf_set_freq_explicit(int(2150e6), int(100e6), pyhackrf.py_rf_path_filter.RF_PATH_FILTER_BYPASS)
```
I think I should add documentation to each function.
You can be sure that the function is applied if an exception is not raised. I process the response from libhackrf and if it is not equal to `HACKRF_SUCCESS` then an exception is raised

**Comment by GvozdevLeonid** [comment]
Overall, this wrapper is written without any modifications, so you can use the original HackRF documentation. There are some changes to add support for callbacks in Python, as well as slightly modified code for Android support (some functions are completely unavailable, such as opening by serial number or retrieving the list of devices).

**Comment by 777arc** [comment]
Ahhh it was the first param, not the third param, that was ultimately causing the error, ty!!!

**Comment by GvozdevLeonid** [comment]
Is your problem solved? Can I close this issue?
