### ISSUE TITLE
PySDR

### ISSUE THREAD

**Issue by 777arc** [GvozdevLeonid/python_hackrf#4]
(not an issue) just thought I would point out I updated https://pysdr.org/content/hackrf.html to have the new callback format where device is specified, I tried to make the receive code example essentially the minimum code needed to do what it does, but if you have any suggestions feel free to use the "suggest an edit" link at the top or bottom of the page

**Comment by GvozdevLeonid** [comment]
I updated the installation and now it should work without problems. Now the search for the hackrf library is done with pkg-config

Also, no need to recalculate gain anymore
```py
allowed_lna_gain = round(max(0, min(40, lna_gain)) / 8) * 8
allowed_vga_gain = round(max(0, min(62, vga_gain)) / 2) * 2
```
I added this code to the lna and vga setup functions.

Also, you can simplify the code a bit using the following construct
```py
to_read = valid_length // 2
accepted_data = (buffer[:to_read:2].astype(np.int8, copy=False) / 128 + 1j * buffer[1:to_read:2].astype(np.int8, copy=False) / 128).astype(np.complex64)
```

Also, probably a simpler way to check whether the library is installed is to call the command in the terminal
`python_hackrf info`
