### ISSUE TITLE
Invalid value encountered in cast when using pyhackrf_transfer

### ISSUE THREAD

**Issue by videah** [GvozdevLeonid/python_hackrf#6]
Currently running into an issue where providing a file I have previously recorded to `pyhackrf_transfer` causes some errors:

```sh
call pyhackrf_set_sample_rate(2.000 MHz)
call pyhackrf_set_baseband_filter_bandwidth(1.750 MHz)
call pyhackrf_set_freq(868300000 Hz / 868.300 MHz)
call pyhackrf_set_amp_enable(True)
Traceback (most recent call last):
  File "python_hackrf/pyhackrf_tools/pyhackrf_transfer.pyx", line 167, in python_hackrf.pyhackrf_tools.pyhackrf_transfer.tx_callback
RuntimeWarning: invalid value encountered in cast
```

**Comment by GvozdevLeonid** [comment]
Hello @videah . Can you show what parameters you set for transfer?

**Comment by videah** [comment]
Ahh I missed that part, sorry for the bother! It might makes sense to emphasize this more or even throw a warning when trying to pass data from the official tools in.

**Comment by GvozdevLeonid** [comment]
I decided to choose this format so that the user does not need to apply additional manipulations to the data to get the IQ
